FROM jenkins/jenkins

USER root

RUN apt-get update
RUN apt-get install curl libunwind8 gettext apt-transport-https -y
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/dotnetdev.list'

RUN apt-get update
RUN apt-get install dotnet-sdk-2.0.0 -y

RUN export PATH=$PATH:$HOME/dotnet
